name: Criar Release

on:
  - push

env:
  RELEASE_FILENAME: "refund-last-purchase.zip"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Baixar arquivo de dependência
        run: curl -o controladoUtils.js https://raw.githubusercontent.com/controlado/pengu-plugins/master/controladoUtils.js

      - name: Criar arquivo ZIP
        run: zip -r ${{ env.RELEASE_FILENAME }} . -x ".git/*" ".github/*"

      - name: Criar Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Plugin ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Adicionar arquivo ZIP à Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_FILENAME }}
          asset_name: ${{ env.RELEASE_FILENAME }}
          asset_content_type: application/zip
